//import "oaidl.idl";
//import "ocidl.idl";

import "unknwn.idl";
[ object, uuid(10000001-0000-0000-0000-000000000001) ]
interface ISum : IUnknown
{
HRESULT Sum(int x, int y, [out, retval] int* retval);
}

[ uuid(10000003-0000-0000-0000-000000000001),
helpstring("Inside COM+ Component Type Library"),
version(1.0) ]
library Component
{
importlib("stdole32.tlb");

[ uuid(10000002-0000-0000-0000-000000000001) ]
coclass InsideCOM
{
interface ISum;
}
};